## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [128]:
a = np.random.randint(-10,10,15)
print(a)
a[(a>3)&(a<8)] *=-1
print(a)

[-2 -1  0 -2  3  6  2 -5  1  2  7 -1 -4  9 -5]
[-2 -1  0 -2  3 -6  2 -5  1  2 -7 -1 -4  9 -5]


**2.** Заменить максимальный элемент случайного массива на 0

In [100]:
b = np.random.randint(-10,10,15)
print(b)
b[np.argmax(b)] = 0
print(b)


[ 7  6 -1 -5  4 -3  5  8  4  4 -5  5  8 -8  3]
[ 7  6 -1 -5  4 -3  5  0  4  4 -5  5  8 -8  3]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [97]:
c = np.random.randint(-10, 10, [3,3])
print(c)
print('«----------«')
d = np.random.randint(-10, 10, [3,3])
print(d)
print('«----------«')
e = np.dot(c,d)
print(e)
print('«----------«')
f = np.matmul(c,d)
print(f)
print('«----------«')
g = np.multiply(c,d) #What we exactly need
print(g)

[[-9 -7 -7]
 [-7 -1 -8]
 [-8  7  4]]
«----------«
[[  0   8   9]
 [ -5   7  -9]
 [-10  -9   0]]
«----------«
[[ 105  -58  -18]
 [  85    9  -54]
 [ -75  -51 -135]]
«----------«
[[ 105  -58  -18]
 [  85    9  -54]
 [ -75  -51 -135]]
«----------«
[[  0 -56 -63]
 [ 35  -7  72]
 [ 80 -63   0]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [6]:
A = np.random.randint(-5,5,(8,3))
B = np.random.randint(-5,5,(2,2))
print(A)
print(B)
C = (A[..., np.newaxis, np.newaxis] == B)
print(C)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[[ 4 -1  1]
 [ 1  0  4]
 [ 1  0  2]
 [ 1  3  3]
 [-2 -4  4]
 [-5 -3 -4]
 [ 2  0  2]
 [-4 -1  1]]
[[3 2]
 [0 1]]
[[[[False False]
   [False False]]

  [[False False]
   [False False]]

  [[False False]
   [False  True]]]


 [[[False False]
   [False  True]]

  [[False False]
   [ True False]]

  [[False False]
   [False False]]]


 [[[False False]
   [False  True]]

  [[False False]
   [ True False]]

  [[False  True]
   [False False]]]


 [[[False False]
   [False  True]]

  [[ True False]
   [False False]]

  [[ True False]
   [False False]]]


 [[[False False]
   [False False]]

  [[False False]
   [False False]]

  [[False False]
   [False False]]]


 [[[False False]
   [False False]]

  [[False False]
   [False False]]

  [[False False]
   [False False]]]


 [[[False  True]
   [False False]]

  [[False False]
   [ True False]]

  [[False  True]
   [False False]]]


 [[[False False]
   [False False]]

  [[False False]
   [False False]]

  [[False False]
   [False  True]]]]
[1 2 3 6]

**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [119]:
A = np.random.randint(0,5,(10,3))
B = np.logical_and.reduce(A[:,1:] == A[:,:-1], axis=1)
C = A[~B]
print(A)
print(C)

[[0 1 0]
 [3 4 1]
 [1 0 0]
 [1 4 2]
 [1 3 3]
 [0 3 1]
 [4 4 2]
 [0 1 2]
 [3 3 3]
 [2 4 2]]
[[0 1 0]
 [3 4 1]
 [1 0 0]
 [1 4 2]
 [1 3 3]
 [0 3 1]
 [4 4 2]
 [0 1 2]
 [2 4 2]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [7]:
A = np.random.randint(0, 2, (6,3))
T = np.ascontiguousarray(A).view(np.dtype((np.void, A.dtype.itemsize * A.shape[1])))
_, idx = np.unique(T, return_index=True)
delA = A[idx]
print(A)
print(delA)

[[0 1 0]
 [0 0 0]
 [1 0 0]
 [1 0 0]
 [1 1 0]
 [0 1 1]]
[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 1 0]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [142]:
#numpy
A = np.random.randint(-5, 5, (3,4))
print(A)
print(np.prod(np.diag(A)[np.diag(A)!=0])*np.prod(np.diag(A, k=+1)[np.diag(A, k=+1)!=0]))
#python
iter1 = -1
iter2 = -1
v = 1
for a in A:
    iter1 = iter1 + 1
    iter2 = iter2 + 1
    if (iter1 < A.shape[0]) and (iter2 < A.shape[1]):
        if A[iter1,iter2] != 0:
            v = v * A[iter1,iter2]
iter1 = -1
iter2 = 0
for a in A:
    iter1 = iter1 + 1
    iter2 = iter2 + 1
    if (iter1 < A.shape[0]) and (iter2 < A.shape[1]):
        if A[iter1,iter2] != 0:
            v = v * A[iter1,iter2]
print(v)

[[-1  2 -4  3]
 [ 3 -5 -4  2]
 [-3  3 -3 -3]]
-360
-360


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [143]:
A = np.random.randint(0,3,3)
B = np.random.randint(0,3,3)
#numpy
AA = np.sort(A)
BB = np.sort(B)
print(A)
print(B)
CC = np.array_equal(AA,BB)
print(CC)
#python
AAA = sorted(A)
BBB = sorted(B)
print(AAA == BBB)

[1 1 0]
[0 1 1]
_______
True
_______
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [121]:
#numpy
A = np.random.randint(-4,4,18)
print(A)
if np.in1d(0,A):
    B =np.append(A[1:],-1)
    print(max(A[B==0]))
else:
    print('0 of 0 exists here)')
#python
max_after_zero = -999
for i in range(len(A)):
    if A[i]==0 and A[i-1] > max_after_zero:
        max_after_zero = A[i-1]
print(max_after_zero)


[ 0  3 -2 -1  2  0 -4  3 -3 -4 -3 -4 -4  3  0 -1 -1 -2]
3
3


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [163]:
#numpy
x = np.random.randint(-3,3,10)
x = np.sort(x)
print(x)
def rle(typicalArray):
        arr = np.asarray(typicalArray)
        n = len(arr)
        if n == 0:
            return None, None, None
        else:
            y = arr[1:] != arr[:-1]
            i = np.append(np.where(y), n - 1)
            z = np.diff(np.append(-1, i))
            p = np.cumsum(np.append(0, z))[:-1]
            return z, p, arr[i]
countOfSymbols, xxx, symbols = rle(x)
print(symbols)
print(countOfSymbols)
print('_____________________________')
#pyhton
from array import *
print(x)
num = []
zn = []
count = 1
for i in range(0,len(x-1)):
    if i+1 < len(x):
        if x[i] == x[i+1]:
            count+= 1
        else:
            zn.append(x[i])
            num.append(count)
            count = 1
    else:
        zn.append(x[i])
        num.append(count)
print(zn)
print(num)

[-3 -3 -2 -2 -1  1  1  2  2  2]
[-3 -2 -1  1  2]
[2 2 1 2 3]
_____________________________
[-3 -3 -2 -2 -1  1  1  2  2  2]
[-3, -2, -1, 1, 2]
[2, 2, 1, 2, 3]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [229]:
from scipy.spatial.distance import cdist
import timeit
#numpy
def EDM(A,B):
    p1 = np.sum(A**2, axis =1)[:, np.newaxis]
    p2 = np.sum(B**2, axis =1)
    p3 = -2 * np.dot(A,B.T)
    return np.sqrt(p1+p2+p3)
#________________________________________________
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[2, 1, 4], [7, 7, 8], [3, 5, 10]])
#print(EDM(A,B))
#print(cdist(A,B))
e_d_m = """
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[2, 1, 4], [7, 7, 8], [3, 5, 10]])
p1 = np.sum(A**2, axis =1)[:, np.newaxis]
p2 = np.sum(B**2, axis =1)
p3 = -2 * np.dot(A,B.T)
np.sqrt(p1+p2+p3)
"""
c_dist = """
from scipy.spatial.distance import cdist
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[2, 1, 4], [7, 7, 8], [3, 5, 10]])
cdist(A,B)
"""
print(EDM(A,B))
print(timeit.timeit(e_d_m, number=1))
print(cdist(A,B))
print(timeit.timeit(c_dist, number=1))
#python
from sklearn.metrics.pairwise import euclidean_distances
print(euclidean_distances(A,B))
euclid_dist = """
from sklearn.metrics.pairwise import euclidean_distances
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[2, 1, 4], [7, 7, 8], [3, 5, 10]])
euclidean_distances(A,B)
"""
print(timeit.timeit(euclid_dist, number=1))

[[1.73205081 9.2736185  7.87400787]
 [4.89897949 4.12310563 4.12310563]
 [9.94987437 1.41421356 5.09901951]]
4.5700000555370934e-05
[[1.73205081 9.2736185  7.87400787]
 [4.89897949 4.12310563 4.12310563]
 [9.94987437 1.41421356 5.09901951]]
2.7800000680144876e-05
[[1.73205081 9.2736185  7.87400787]
 [4.89897949 4.12310563 4.12310563]
 [9.94987437 1.41421356 5.09901951]]
0.00013929999840911478


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [230]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [231]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [237]:
average_calories = calorie_stats.mean()
print(average_calories)
print('Difference between CrunchieMunchies and average calories is: ' + str(round(average_calories-60.0,2)))

106.88311688311688
Difference between CrunchieMunchies and average calories is: 46.88


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [239]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [241]:
median_calories = np.median(calorie_stats)
print('Median: ' + str(median_calories))
print('Average: ' + str(average_calories))

Median: 110.0
Average: 106.88311688311688


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [256]:
for i in range(1,10):
    amount = np.percentile(calorie_stats, i)
    print(str(round(amount,2)) + '  ->  ' + str(i))
    if amount > 60:
        nth_percentile = i
        break

50.0  ->  1
50.0  ->  2
55.6  ->  3
70.0  ->  4


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [259]:
more_calories = np.mean(calorie_stats > 60)*100
print(str(round(more_calories,1)) + '%')

96.1%


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [260]:
calorie_std = np.std(calorie_stats)
print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [167]:
#There are significant variations in the health of the cereals available to you. 96% of 77 surveyed cereals had higher calorie counts than
#CrunchieMunchies. CrunchieMunchies may produce weightlose with regular exercise. Mycrunch wins against another companies as its product has
# less than 40% calories